apiVersion: v1
kind: Pod
metadata:
  name: evidence-test-pod-v2
  namespace: test-evidence
  labels:
    app: evidence-test
    created-by: guidepoint-automation
    version: v2-fixed
spec:
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - name: test-container
    image: busybox:latest
    command: ["sleep", "3600"]  # Simple container that will run successfully
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
      requests:
        memory: "32Mi"
        cpu: "25m"
    volumeMounts:
    - name: tmp
      mountPath: /tmp
  volumes:
  - name: tmp
    emptyDir: {}