# GuidePoint Model Client Configuration

model_client:
  name: "GuidePoint AI/ML Client"
  version: "1.0.0"
  role: "AI Model Integration Layer"

capabilities:
  ai_model_integration:
    enabled: true
    features:
      - james_mlops_integration
      - multi_model_support
      - model_selection_optimization
      - performance_optimization
      - cost_optimization

  security_intelligence:
    enabled: true
    features:
      - vulnerability_analysis
      - threat_intelligence
      - compliance_intelligence
      - business_impact_analysis
      - predictive_security

  performance_optimization:
    enabled: true
    features:
      - high_throughput_processing
      - async_processing
      - connection_pooling
      - intelligent_caching
      - load_balancing

james_mlops_integration:
  enabled: true
  endpoint: "http://localhost:8005"
  api_key: "${JAMES_MLOPS_API_KEY}"
  timeout: 10
  retry_attempts: 3

  prediction_endpoints:
    vulnerability_confidence: "/predict/vulnerability_confidence"
    threat_assessment: "/predict/threat_assessment"
    compliance_analysis: "/predict/compliance_analysis"
    business_impact: "/predict/business_impact"

  batch_processing:
    enabled: true
    max_batch_size: 100
    batch_timeout: 30

  performance_monitoring:
    enabled: true
    metrics_collection: true
    latency_tracking: true
    accuracy_monitoring: true

external_models:
  openai:
    enabled: false
    api_key: "${OPENAI_API_KEY}"
    models:
      gpt4: "gpt-4"
      gpt4_turbo: "gpt-4-turbo"
      gpt35_turbo: "gpt-3.5-turbo"
    timeout: 30
    max_tokens: 4000
    temperature: 0.1

  anthropic:
    enabled: false
    api_key: "${ANTHROPIC_API_KEY}"
    models:
      claude3_opus: "claude-3-opus"
      claude3_sonnet: "claude-3-sonnet"
      claude3_haiku: "claude-3-haiku"
    timeout: 30
    max_tokens: 4000
    temperature: 0.1

  azure_openai:
    enabled: false
    endpoint: "${AZURE_OPENAI_ENDPOINT}"
    api_key: "${AZURE_OPENAI_API_KEY}"
    api_version: "2024-02-01"
    deployment_names:
      gpt4: "gpt-4-deployment"
      embedding: "text-embedding-ada-002"

  local_models:
    enabled: true
    ollama_endpoint: "http://localhost:11434"
    models:
      - name: "llama3"
        context_window: 8192
        use_cases: ["general_analysis", "code_review"]
      - name: "mistral"
        context_window: 32768
        use_cases: ["security_analysis", "compliance"]
      - name: "james"
        context_window: 4096
        use_cases: ["security_consulting", "vulnerability_analysis"]

intelligence_services:
  vulnerability_intelligence:
    enabled: true
    features:
      - risk_scoring
      - exploitability_assessment
      - fix_confidence_prediction
      - business_impact_analysis
      - remediation_prioritization

    models:
      primary: "james_mlops"
      fallback: "local_models"
      ensemble: true

  threat_intelligence:
    enabled: true
    features:
      - threat_pattern_recognition
      - attack_vector_analysis
      - threat_landscape_analysis
      - predictive_threat_modeling
      - intelligence_correlation

    data_sources:
      - mitre_attack
      - cve_database
      - threat_feeds
      - historical_incidents

  compliance_intelligence:
    enabled: true
    features:
      - compliance_gap_analysis
      - control_effectiveness_assessment
      - regulatory_impact_analysis
      - compliance_trend_analysis
      - audit_preparation_intelligence

    frameworks:
      - soc2
      - pci_dss
      - gdpr
      - iso27001
      - hipaa

  business_intelligence:
    enabled: true
    features:
      - security_business_impact
      - cost_benefit_analysis
      - risk_tolerance_modeling
      - strategic_planning
      - executive_reporting

    metrics:
      - roi_calculation
      - risk_quantification
      - business_alignment
      - decision_support

model_optimization:
  model_selection:
    enabled: true
    criteria:
      - accuracy_requirements
      - latency_requirements
      - cost_constraints
      - context_size_needs
      - domain_expertise

    fallback_strategy:
      enabled: true
      fallback_order: ["james_mlops", "local_models", "external_apis"]
      retry_attempts: 2

  performance_optimization:
    caching:
      enabled: true
      cache_backend: "redis"
      cache_ttl: 3600  # 1 hour
      cache_size_limit: "1GB"

    connection_pooling:
      enabled: true
      pool_size: 20
      max_overflow: 10
      pool_timeout: 30

    batch_processing:
      enabled: true
      max_batch_size: 50
      batch_timeout: 10
      auto_batching: true

  cost_optimization:
    enabled: true
    budget_limits:
      daily_limit: 100.00
      monthly_limit: 2000.00
      per_request_limit: 5.00

    cost_tracking:
      enabled: true
      cost_breakdown: true
      usage_analytics: true
      cost_alerts: true

data_processing:
  input_processing:
    enabled: true
    features:
      - data_validation
      - feature_extraction
      - context_enrichment
      - normalization
      - anonymization

    validation_rules:
      - required_fields
      - data_types
      - value_ranges
      - security_constraints

  output_processing:
    enabled: true
    features:
      - result_validation
      - confidence_scoring
      - result_formatting
      - standardization
      - quality_assessment

    quality_metrics:
      - confidence_threshold: 0.8
      - accuracy_requirement: 0.9
      - consistency_check: true
      - business_validation: true

security:
  data_protection:
    enabled: true
    encryption_at_rest: true
    encryption_in_transit: true
    pii_detection: true
    data_anonymization: true

  access_control:
    enabled: true
    api_key_required: true
    role_based_access: true
    rate_limiting: true

  audit_logging:
    enabled: true
    log_all_requests: true
    log_all_responses: false  # Due to potentially large size
    log_metadata: true
    retention_days: 365

monitoring:
  performance_monitoring:
    enabled: true
    metrics:
      - request_latency
      - throughput
      - error_rates
      - model_accuracy
      - resource_utilization

    alerts:
      - high_latency: "> 5 seconds"
      - low_accuracy: "< 85%"
      - high_error_rate: "> 5%"
      - resource_exhaustion: "> 90%"

  cost_monitoring:
    enabled: true
    tracking:
      - api_costs
      - compute_costs
      - storage_costs
      - total_costs

    budgets:
      - daily_budget: 100.00
      - monthly_budget: 2000.00
      - cost_per_prediction: 0.50

  health_monitoring:
    enabled: true
    health_checks:
      - model_availability
      - api_connectivity
      - cache_health
      - database_connectivity

    intervals:
      health_check: 30  # seconds
      performance_check: 60  # seconds
      cost_check: 300  # 5 minutes

integrations:
  gp_scanner:
    enabled: true
    real_time_analysis: true
    vulnerability_enhancement: true
    risk_assessment: true

  gp_remediation:
    enabled: true
    fix_confidence_prediction: true
    success_probability_analysis: true
    remediation_planning: true

  gp_intelligence:
    enabled: true
    risk_quantification: true
    business_impact_analysis: true
    threat_intelligence_fusion: true

  gp_escalation:
    enabled: true
    escalation_decision_support: true
    priority_assessment: true
    resource_allocation: true

  external_systems:
    vulnerability_databases:
      - nvd
      - mitre_cve
      - github_advisories

    threat_intelligence:
      - mitre_attack
      - sans
      - owasp

    business_systems:
      - cmdb
      - asset_management
      - risk_management

logging:
  level: "INFO"
  structured_logging: true
  log_rotation: "daily"
  max_file_size: "100MB"

  categories:
    model_requests: "INFO"
    performance_metrics: "DEBUG"
    security_events: "WARNING"
    cost_tracking: "INFO"
    errors: "ERROR"

development:
  debug_mode: false
  test_mode: false
  mock_models: false
  verbose_logging: false
  performance_profiling: false

  testing:
    unit_tests: true
    integration_tests: true
    performance_tests: true
    accuracy_tests: true