name: Dependency Security Updates

# Automated dependency updates with security focus
# Creates PRs for vulnerable dependencies

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    name: Update Vulnerable Dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        if: hashFiles('**/package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Python
        if: hashFiles('**/requirements.txt') != ''
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Update npm dependencies
        if: hashFiles('**/package.json') != ''
        id: npm-update
        run: |
          echo "→ Checking npm vulnerabilities..."
          npm audit --json > npm-audit-before.json || true

          echo "→ Applying npm audit fix..."
          npm audit fix --force

          echo "→ Checking remaining vulnerabilities..."
          npm audit --json > npm-audit-after.json || true

          BEFORE=$(jq '.metadata.vulnerabilities | to_entries | map(.value) | add' npm-audit-before.json)
          AFTER=$(jq '.metadata.vulnerabilities | to_entries | map(.value) | add' npm-audit-after.json)

          echo "npm-before=$BEFORE" >> $GITHUB_OUTPUT
          echo "npm-after=$AFTER" >> $GITHUB_OUTPUT

      - name: Update Python dependencies
        if: hashFiles('**/requirements.txt') != ''
        id: pip-update
        run: |
          pip install pip-audit

          echo "→ Checking Python vulnerabilities..."
          pip-audit --format json > pip-audit-before.json || true

          echo "→ Applying pip-audit fix..."
          pip-audit --fix || true

          pip-audit --format json > pip-audit-after.json || true

          BEFORE=$(jq '. | length' pip-audit-before.json)
          AFTER=$(jq '. | length' pip-audit-after.json)

          echo "pip-before=$BEFORE" >> $GITHUB_OUTPUT
          echo "pip-after=$AFTER" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            chore(deps): Security update - fix vulnerable dependencies

            - npm vulnerabilities: ${{ steps.npm-update.outputs.npm-before || 0 }} → ${{ steps.npm-update.outputs.npm-after || 0 }}
            - pip vulnerabilities: ${{ steps.pip-update.outputs.pip-before || 0 }} → ${{ steps.pip-update.outputs.pip-after || 0 }}

            🤖 Automated dependency security update
          branch: deps/security-update
          delete-branch: true
          title: '🔒 Security: Update vulnerable dependencies'
          body: |
            ## 🔒 Automated Security Dependency Update

            This PR updates dependencies with known security vulnerabilities.

            ### npm (Node.js)
            - Before: ${{ steps.npm-update.outputs.npm-before || 0 }} vulnerabilities
            - After: ${{ steps.npm-update.outputs.npm-after || 0 }} vulnerabilities
            - Fixed: ${{ steps.npm-update.outputs.npm-before || 0 - steps.npm-update.outputs.npm-after || 0 }}

            ### pip (Python)
            - Before: ${{ steps.pip-update.outputs.pip-before || 0 }} vulnerabilities
            - After: ${{ steps.pip-update.outputs.pip-after || 0 }} vulnerabilities
            - Fixed: ${{ steps.pip-update.outputs.pip-before || 0 - steps.pip-update.outputs.pip-after || 0 }}

            ### Testing Required
            - [ ] Run full test suite
            - [ ] Verify no breaking changes
            - [ ] Check application functionality

            ---
            🤖 Auto-generated by GitHub Actions
          labels: |
            security
            dependencies
            automated
