# GP-Copilot Platform Configuration
# Central configuration for all platform services and integrations

platform:
  name: "GP-Copilot Security Platform"
  version: "1.0.0"
  environment: "production"  # production | staging | development

# Data persistence configuration
data:
  base_path: "/home/jimmie/linkops-industries/GP-copilot/GP-DATA"
  archive_retention_days: 90
  backup_enabled: true
  backup_schedule: "daily"

# Scanner configuration defaults
scanners:
  enabled:
    - trivy
    - bandit
    - semgrep
    - checkov
    - gitleaks
    - opa

  timeout_seconds: 300
  parallel_execution: true
  max_parallel_jobs: 4

  output_format: "json"  # json | sarif | html
  severity_threshold: "MEDIUM"  # LOW | MEDIUM | HIGH | CRITICAL

# OPA Policy Engine settings
opa:
  enabled: true
  policy_path: "../GP-CONSULTING-AGENTS/policies/opa"
  decision_log_enabled: true
  bundle_mode: false

  enforcement_mode: "enforce"  # monitor | warn | enforce

  namespaces:
    - kubernetes.admission
    - infrastructure.compliance
    - security.baseline

# Reporting configuration
reporting:
  default_format: "markdown"
  include_remediation: true
  include_compliance_mapping: true

  compliance_frameworks:
    - CIS
    - SOC2
    - NIST
    - PCI-DSS
    - HIPAA

# Integration settings
integrations:
  github:
    enabled: false
    api_endpoint: "https://api.github.com"

  slack:
    enabled: false
    webhook_url: ""

  email:
    enabled: false
    smtp_server: ""

# Security settings
security:
  secrets_scanning: true
  credential_detection: true
  api_key_rotation_days: 90

  encryption:
    at_rest: true
    in_transit: true
    algorithm: "AES-256-GCM"

# Performance tuning
performance:
  cache_enabled: true
  cache_ttl_seconds: 3600

  resource_limits:
    max_memory_gb: 8
    max_cpu_cores: 4

# Logging configuration
logging:
  level: "INFO"  # DEBUG | INFO | WARNING | ERROR | CRITICAL
  format: "json"

  destinations:
    - console
    - file

  file_path: "/var/log/gp-copilot/platform.log"
  max_file_size_mb: 100
  max_files: 10

# Agent configuration
agents:
  james_brain:
    enabled: true
    model: "local"
    temperature: 0.3

  consulting_agents:
    enabled: true
    auto_remediation: false
    approval_required: true