# SecOps Configuration - HEALTHCARE Project
project:
  name: "HealthVault"
  industry: "healthcare"
  compliance_frameworks:
    - "HIPAA"
    - "HITECH"
    - "SOC2-Type-II"

scanning:
  enabled_scanners:
    - tfsec
    - checkov
    - bandit
    - trivy
    - gitleaks
    - opa

  scan_paths:
    terraform: "./infrastructure/terraform"
    backend: "./backend"

  severity_thresholds:
    fail_on_critical: true
    fail_on_high: true
    fail_on_medium: true  # Stricter for HIPAA

policies:
  opa_policies:
    - "cloud-security-patterns/vpc-isolation"
    - "cloud-security-patterns/private-cloud-access"  # No internet egress for PHI
    - "cloud-security-patterns/visibility-monitoring"
    - "compliance-frameworks/hipaa"

  enforcement_mode: "strict"

encryption:
  require_kms: true           # HIPAA requires KMS
  require_encryption_at_rest: true
  require_encryption_in_transit: true

aws:
  region: "us-east-1"
