# GuidePoint DevSecOps Agent Configuration

agent:
  name: "GuidePoint DevSecOps"
  version: "1.0.0"
  role: "CI/CD Security & Secrets Management"

capabilities:
  secrets_management:
    enabled: true
    features:
      - vault_integration
      - aws_secrets_manager
      - kubernetes_secrets
      - secret_rotation
      - secret_scanning

  pipeline_security:
    enabled: true
    features:
      - github_actions_security
      - gitlab_ci_integration
      - jenkins_security
      - azure_devops_integration
      - security_gates

  compliance_automation:
    enabled: true
    features:
      - soc2_automation
      - pci_dss_validation
      - gdpr_compliance
      - iso27001_controls
      - audit_logging

  policy_enforcement:
    enabled: true
    features:
      - opa_integration
      - security_policies
      - admission_controllers
      - compliance_policies
      - custom_policies

secrets_backends:
  vault:
    enabled: true
    url: "${VAULT_URL:-https://vault.company.com:8200}"
    auth_method: "kubernetes"
    mount_path: "secret"
    policies_path: "auth/kubernetes"

  aws_secrets_manager:
    enabled: true
    region: "${AWS_REGION:-us-east-1}"
    auto_rotation: true
    kms_key_id: "${AWS_KMS_KEY_ID}"

  kubernetes_secrets:
    enabled: true
    sealed_secrets:
      enabled: true
      controller_name: "sealed-secrets-controller"
      controller_namespace: "kube-system"
    external_secrets:
      enabled: true
      operator_namespace: "external-secrets-system"

  azure_key_vault:
    enabled: false
    vault_url: "${AZURE_VAULT_URL}"
    tenant_id: "${AZURE_TENANT_ID}"
    client_id: "${AZURE_CLIENT_ID}"

pipeline_integrations:
  github_actions:
    enabled: true
    features:
      - workflow_security
      - secret_scanning
      - dependency_scanning
      - container_scanning
      - compliance_checks

  gitlab_ci:
    enabled: true
    features:
      - security_templates
      - sast_integration
      - dast_integration
      - container_scanning
      - license_compliance

  jenkins:
    enabled: true
    features:
      - pipeline_security
      - credential_management
      - plugin_security
      - build_security
      - audit_integration

  azure_devops:
    enabled: true
    features:
      - security_extensions
      - pipeline_security
      - artifact_security
      - compliance_validation

security_policies:
  secrets_scanning:
    mode: "block_on_detection"
    exceptions: []
    notification_channels: ["slack", "email"]

  vulnerability_threshold:
    critical: "block"
    high: "block"
    medium: "warn"
    low: "allow"

  compliance_enforcement:
    mode: "strict"
    frameworks: ["soc2", "pci_dss", "gdpr"]
    exceptions_require_approval: true

  access_control:
    require_mfa: true
    session_timeout: 3600
    role_based_access: true
    principle: "least_privilege"

compliance_frameworks:
  soc2:
    enabled: true
    controls:
      - CC1  # Control Environment
      - CC2  # Communication and Information
      - CC3  # Risk Assessment
      - CC4  # Monitoring Activities
      - CC5  # Control Activities
      - CC6  # Logical and Physical Access
      - CC7  # System Operations
      - CC8  # Change Management
      - CC9  # Risk Mitigation
    evidence_collection: "automated"

  pci_dss:
    enabled: true
    requirements:
      - "1"   # Firewall Configuration
      - "2"   # Default Passwords
      - "3"   # Cardholder Data Protection
      - "4"   # Encryption in Transit
      - "6"   # Secure Development
      - "7"   # Access Control
      - "8"   # Authentication
      - "10"  # Logging and Monitoring
      - "11"  # Security Testing
      - "12"  # Security Policies
    assessment_frequency: "quarterly"

  gdpr:
    enabled: true
    articles:
      - "25"  # Data Protection by Design
      - "32"  # Security of Processing
      - "33"  # Breach Notification
      - "35"  # Data Protection Impact Assessment
    privacy_controls: "enabled"

  iso27001:
    enabled: true
    controls:
      - "A.5"   # Information Security Policies
      - "A.6"   # Organization of Information Security
      - "A.7"   # Human Resource Security
      - "A.8"   # Asset Management
      - "A.9"   # Access Control
      - "A.10"  # Cryptography
      - "A.12"  # Operations Security
      - "A.13"  # Communications Security
      - "A.14"  # System Acquisition
      - "A.16"  # Information Security Incident Management
      - "A.17"  # Business Continuity
      - "A.18"  # Compliance
    maturity_level: "managed"

integrations:
  gp_scanner:
    enabled: true
    real_time_validation: true
    security_gates: true
    compliance_scanning: true

  gp_intelligence:
    enabled: true
    risk_quantification: true
    threat_intelligence: true
    business_impact_analysis: true

  gp_escalation:
    enabled: true
    auto_escalation: true
    incident_response: true
    notification_workflows: true

  gp_data_machine:
    enabled: true
    security_analytics: true
    pattern_recognition: true
    predictive_security: true

monitoring:
  metrics_collection:
    enabled: true
    prometheus_integration: true
    grafana_dashboards: true
    custom_metrics: true

  alerting:
    enabled: true
    channels:
      - type: "pagerduty"
        api_key: "${PAGERDUTY_API_KEY}"
        service_key: "${PAGERDUTY_SERVICE_KEY}"
      - type: "slack"
        webhook_url: "${SLACK_WEBHOOK_URL}"
        channel: "#security-alerts"
      - type: "email"
        smtp_server: "${SMTP_SERVER}"
        recipients: ["security-team@company.com"]

  logging:
    enabled: true
    level: "INFO"
    structured_logging: true
    audit_logging: true
    retention_days: 2555  # 7 years

security:
  encryption:
    algorithm: "AES-256-GCM"
    key_management: "HSM"
    transit_encryption: true
    at_rest_encryption: true

  access_control:
    type: "RBAC"
    require_2fa: true
    session_timeout: 3600
    password_policy:
      min_length: 14
      require_special_chars: true
      require_numbers: true
      require_uppercase: true

  audit_logging:
    enabled: true
    log_level: "detailed"
    retention_days: 2555
    immutable_logs: true

  network_security:
    tls_version: "1.3"
    cipher_suites: ["TLS_AES_256_GCM_SHA384", "TLS_CHACHA20_POLY1305_SHA256"]
    certificate_management: "automated"

performance:
  response_time_sla: 2  # seconds
  concurrent_operations: 100
  secret_rotation_interval: "24h"
  policy_evaluation_timeout: "5s"
  cache_ttl: "300s"

development:
  debug_mode: false
  test_mode: false
  development_vault: false
  mock_integrations: false