apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  containers:
  - image: nginx:latest
    name: test-container
    securityContext:
      privileged: true
      runAsUser: 0
